global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ethereum-monitor'
    region: 'singapore'

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'nethermind'
    static_configs:
      - targets: ['nethermind:9091']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true


alerting:
  alertmanagers:
    - static_configs:
        - targets: []